# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a7988ddccf56f57b3a96ca9b7ce8c4ac27123b2c48101080781c9c5da1c6023a5a25fae4677975dde0fb82742950232f5e0795f6d05fe58a872fa9f5ac15a13

test:
  secret_key_base: a3a6a056bf39bcc48dea2fe4e7e25e147b3710a3c841a5c549ad6ad080db39f4000ed62cf1f161856eeed47bc7c9623050c5c435ad54f68855f2ec511a327d5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
